from Custom_Widgets.LoadingIndicators.QCustomArcLoader import QCustomArcLoader
from Custom_Widgets.LoadingIndicators.QCustom3CirclesLoader import QCustom3CirclesLoader
from Custom_Widgets.LoadingIndicators.QCustomPerlinLoader import QCustomPerlinLoader
